### ISSUE TITLE
Incompatibility with Optifine

### ISSUE THREAD

**Issue by Dalethmann** [Nyphet/just-vertical-slabs#1]
Mod encounters texture corruption with optifine installed. Minecraft will launch without error yet (nearly) all textures for the included vertical slabs will be corrupted beyond recognition. Slabs that are not corrupted are oak vertical slabs. 

Issues encountered when running the following:
Minecraft 1.18.2
forge-1.18.2-40.1.0
justverticalslabs-1.18.2-2.0.0.0
OptiFine_1.18.2_HD_U_H7

**Comment by Crystal-Spider** [comment]
Hi! I was able to replicate the issue.  
It looks like that enabling any kind of shaders messes up with how I'm copying the textures from other blocks.  
I will try to solve this as fast as I can, meanwhile to have textures work with Optifine you should make sure that in Optifine shaders option "OFF" is selected.  
I'm sorry for the inconvenience.

**Comment by Crystal-Spider** [comment]
So, I managed to fix that. In a few days I will release a new version, 1.18.2-3.0.0.0. There the bug will be fixed, along with other improvements and more bug fixes.  
I will notify here again when I'll release the version and close the issue, thank you for reporting this bug!

**Comment by Crystal-Spider** [comment]
Okay, new release has been published!  
In version [1.18.2-3.0.0.0](https://github.com/Nyphet/just-vertical-slabs/releases/tag/v1.18.2-3.0.0.0) this bug should be fixed so I'm closing the issue.
