### ISSUE TITLE
Game Crashed While Using Creative Tab

### ISSUE THREAD

**Issue by CattyBarry** [Nyphet/just-vertical-slabs#18]
**Describe the bug**
The Game crashed while I was looking at the vertical slabs creative tab

**To Reproduce**
1. Go to the creative tab
3. Scroll down the list
4. Game may crash

**Expected behavior**
Doesnt crash

**Screenshots**

**Stacktrace and logs**
https://crashy.net/uj68N2N5hen2oyOQaNeh

**System information:**
 - OS:  Windows 10
 - Minecraft version: 1.18.2, Forge 40.1.60
 - Release version: 1.18.2-3.2.0.0
 - Other mods installed that add slabs: Entire modlist provided in Crashy

**Additional context**
Let me know if you have any questions or want a zip of the modpack I'm running. Its custom and very new so I'm expecting lots to break

**Comment by Nyphet** [comment]
Does it crash only sometimes? Also what are the Vertical Slabs at the end of the inventory tab? What version of the mod are you using?

**Comment by Nyphet** [comment]
Actually just tell me if the crash doesn't happens every time, I figured out the other infos I needed from the link you provided.

**Comment by Crystal-Spider** [comment]
Solved with [Release 1.18.2-3.2.0.1](https://github.com/Nyphet/just-vertical-slabs/releases/tag/v1.18.2-3.2.0.1).  
It will be available for download on Curseforge soon.
