### ISSUE TITLE
Copper shingles from Create do not get recognized

### ISSUE THREAD

**Issue by utterlynowhere** [Nyphet/just-vertical-slabs#21]
Vertical Slabs for Create's Copper Shingle Slabs do not generate

1. Install Just Vertical Slabs
2. Install Create
3. Open inventory
4. Type Copper Shingle Slab

Vertical Copper Shingle Slabs should have been generated. 

**System information:**
 - OS:  Windows
 - Minecraft version: 1.18.2
 - Release version: justverticalslabs-1.18.2-3.2.0.1-forge.jar
 - Create, Malum, Twigs, Architect's Palette (all of these mods have vertical slabs except for the copper shingles one from Create)
 

![2022-07-18_19 30 23](https://user-images.githubusercontent.com/37447851/179502634-60e6cc16-c8a2-4938-a422-91d04b580f21.png)

**Comment by Crystal-Spider** [comment]
This is not a problem with my mod, rather with Create.  
Those slab items do not have the _minecraft:slabs_ tag, so they can't be detected as slabs.  
To solve the issue please open another issue with Create asking to add the proper tag for those items, if you want you can also link this issue to explain why it can be important.

**Comment by utterlynowhere** [comment]
Thank you for pointing that out! Manually tagging it with datapacks works pretty well.
