### ISSUE TITLE
[1.18.2Forge]Appears in JEI but no recipes

### ISSUE THREAD

**Issue by karikusa** [Nyphet/just-vertical-slabs#27]
OS:windows11home
Minecraft version: 1.18.2
Release version:justverticalslabs-1.18.2-4.0.0.0-forge

**Describe the bug**
Justverticalslabs items are displayed in JEI's recipe search
i can't see the recipe

**Expected behavior**
Pressing R in JEI will bring up a recipe for making a VerticalSlab.

Later, I think it's a bug related to this
Cannot be automatically created by ThermalSeries SequentialFabricator,
It seems that ImmersiveEngineering's Assembler can be created.

**Comment by Crystal-Spider** [comment]
Duplicate #7 
Unfortunately I need to rewrite this mod to make it more compatible, but I won't have time to do this at least until September
