### ISSUE TITLE
Mod not functioning

### ISSUE THREAD

**Issue by InterruptingOctopus** [Nyphet/just-vertical-slabs#3]
I cant seem to get the mod to work, at first i thought it was a mod conflict maybe with another slab mod like klee or even quark's vertical slab feature but after creating a new instance with only JEI, controlling and justverticalslabs i still dont see any generated vertical slabs, nor do i see the mod's creative tab. was there some initial setup i was supposed to do?

**Comment by Crystal-Spider** [comment]
That's weird, there should be no setup required.  
Could you please provide a list of mods you tested it with and also state their version?  
For instance:
- JEI forge-1.18.2-9.5.5.174
- Controlling forge-1.18.2-9.0+19
- JustVerticalSlabs 3.1.0.1
- Forge 40.1.0
- etc.

Note that this mod is compatible with JEI, but not integrated yet, which means you won't be able to see vertical slabs or their recipes with JEI. This is a feature I intend to add in a future version, but for the time being be aware that this behavior is to be expected.

**Comment by InterruptingOctopus** [comment]
of course,
-Controlling-forge-1.18.2-9.0+19
-jei-1.18.2-9.7.0.196
-justverticalslabs-1.18.2-3.1.0.1 the beta is also not functioning
-Forge-1.18.2-40.1.30

**Comment by Crystal-Spider** [comment]
I couldn't replicate the issue. I will leave the setup of the custom profile and some screenshots:
![image](https://user-images.githubusercontent.com/65339023/172552077-39d519f2-a870-46ec-865f-b2230845fbfa.png)
![2022-06-08_08 55 54](https://user-images.githubusercontent.com/65339023/172552140-c2681472-c6a9-4f48-8fc3-40899898522d.png)
![2022-06-08_08 56 07](https://user-images.githubusercontent.com/65339023/172552142-fef34db4-0ca7-4bb1-a20a-71ee7401db30.png)
![2022-06-08_08 56 33](https://user-images.githubusercontent.com/65339023/172552146-b8585cf1-bcf6-46e3-99be-20908257a3f7.png)
Could you please check again whether it's actually working and, if not, could you provide the log?

**Comment by InterruptingOctopus** [comment]
oh i should mention that this is using the GDlauncher if that matters at all

**Comment by Crystal-Spider** [comment]
It should not matter, but just to be sure it would be helpful if you could also provide the launcher log.  
To find the Minecraft log you can refer to this: https://github.com/gorilla-devs/GDLauncher/issues/234
To find the launcher log you can refer to this: https://github.com/gorilla-devs/GDLauncher/wiki/Console-and-Log

**Comment by InterruptingOctopus** [comment]
heres my minecraft log at least
[log.txt](https://github.com/Nyphet/just-vertical-slabs/files/8859184/log.txt)

**Comment by Crystal-Spider** [comment]
From the log it looks like the mod is not installed at all. In the mod discovering section it says:
- Found mod file **Controlling-forge-1.18.2-9.0+19.jar** of type MOD with locator {mods folder locator at C:\_gdl\instances\Test\mods} _(Controlling mod file)_
- Found mod file **jei-1.18.2-9.7.0.196.jar** of type MOD with locator {mods folder locator at C:\_gdl\instances\Test\mods} _(JEI mod file)_
- Found mod file **fmlcore-1.18.2-40.1.30.jar** of type LIBRARY with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@6d366c9b _(Forge stuff)_
- Found mod file **javafmllanguage-1.18.2-40.1.30.jar** of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@6d366c9b _(Forge stuff)_
-Found mod file **mclanguage-1.18.2-40.1.30.jar** of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@6d366c9b _(Forge stuff)_
- Found mod file **client-1.18.2-20220404.173914-srg.jar** of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@6d366c9b _(Forge stuff)_
- Found mod file **forge-1.18.2-40.1.30-universal.jar** of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@6d366c9b _(Forge stuff)_

As you can see this mod file is not listed.
Could you please check if this mod file is present in the mods folder (C:\_gdl\instances\Test\mods)?

**Comment by InterruptingOctopus** [comment]
thats incredibly curious, as it doesnt seem to be despite the launcher saying it is in it's UI...
and yet in my main pack, with a couple over a hundred mods. the jar is certainly in there, but its still acts as if it isnt present at all

**Comment by Crystal-Spider** [comment]
Maybe try to uninstall it from the UI and check if the jar has been removed too (if not just remove it yourself).  
Then try reinstalling it from the UI and check if the jar is now there. If so, you can run Minecraft again and check if it works now.  
If not, it's most probably a problem with the launcher not downloading the jar. In this case you should open an issue on the GDLauncher GitHub and the easiest workaround I can think of would be to manually download the jar yourself for the time being.

Let me know.

**Comment by InterruptingOctopus** [comment]
one thing i did notice whenever i tried to install it through gdlauncher is that it would take forever to "finish".
this only happens with your mod, but basically should i close out of the mod library it will still show as "installed" despite me never actually seeing it confirm it finished installing, but that seems like it'd be for GD like you said.

loading up my main instance i now see the slabs being included, however one thing that might have confused me was trying to search for them in JEI. considering that they are named the same as regular slabs, searchign for them in particular may be a bit of a connudrum. however i suppose one can always search @justverticalslabs to get specifically that type. either way thank you for your help!

Edit: as a matter of fact i had just discovered that using the modname search only results in a result of oak slabs, which i assume might be an NBT issue

Edit2: one more issue i noticed, should the slabs be part of a contraption in the Create mod, they will be rendered as oak slabs instead it would seem.

**Comment by Crystal-Spider** [comment]
About names, I use the same names as the correspondent horizontal slabs for a simple reason: translations. This way there is no need for me or other mod devs to create additional translation files and furthermore this way more languages can easily be supported automatically.  
About JEI, as I said my mod is not integrated yet. I will surely integrate it in the future, but for now JEI is not of use with my mod.  
About Create there is a big problem. My vertical slabs have to use a Block Entity to know which horizontal slab they are "paired" with. Unfortunately Minecraft decided that Block Entity are identified with a position that cannot change, for instance furnaces and chests can't  be pushed by pistons. For this same reason my vertical slab can't be moved once they are placed, otherwise they will lose their BlockEntity and thus use their default properties. You will notice that not only they all render as oak slabs once moved, they will also have missing texture particles and a different sound when breaking or walking on, if there is any sound at all.  
Since I think moving vertical slabs should be possible I have in my todo list to implement a new Block Entity system where they can be moved, thus also allowing chest, furnaces, etc. to be moved too without losing their inventory. However as you may guess this is not an easy task at all, and to be honest it's not even a high priority for now.

Let me know if there is any other problem regarding this issue, for now I'm closing it as solved.
